"""Increase length of password_hash column to 256

Revision ID: 981904d96db5
Revises: 9412f5b9b14c
Create Date: 2024-08-09 00:47:29.010874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981904d96db5'
down_revision = '9412f5b9b14c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
